name: ci-sonarcloud-nodejs
on: 
  pull_request:
    branches:
      - develop


jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run build --if-present
      - run: npm install jest @types/jest sonarqube-scanner --only=dev
      - run: npm run test
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}